version: '3.8'
services:
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=sportverein
      - MARIADB_USER=django
      - MARIADB_PASSWORD=1234
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
  django:
    build: ./django
    links:
      - db
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      - db


